import { describe, it, expect, afterEach, afterAll } from "vitest";
import { z } from "zod";
import { sql } from "drizzle-orm";
import { createTestKit, type TestKit } from "./index";
import { defineTool } from "../define-tool";
import { defineKit } from "../define-kit";
import { kit } from "../result";
import { MigrationError } from "../errors";

// -- Minimal test kit --

const addItem = defineTool({
  name: "add_item",
  description: "Add an item to the inventory",
  args: z.object({
    name: z.string().describe("Item name"),
    quantity: z.number().optional().describe("How many"),
  }),
  handler: async (db, args, ctx) => {
    const id = crypto.randomUUID();
    const qty = args.quantity ?? 1;
    await db.run(sql`INSERT INTO items (id, name, quantity, owner) VALUES (${id}, ${args.name}, ${qty}, ${ctx.userId})`);
    return kit.text(`Added "${args.name}" (qty: ${qty})`);
  },
});

const listItems = defineTool({
  name: "list_items",
  description: "List all items in the inventory",
  args: z.object({}),
  load: async (db) => {
    return db.all<{ id: string; name: string; quantity: number; owner: string }>(
      sql`SELECT * FROM items ORDER BY name`
    );
  },
  handler: async (db, _args, _ctx) => {
    const rows = await db.all<{ name: string; quantity: number }>(
      sql`SELECT * FROM items ORDER BY name`
    );
    if (rows.length === 0) return kit.text("No items.");
    return kit.text(rows.map((r) => `${r.name}: ${r.quantity}`).join("\n"));
  },
});

// load-only tool — handler auto-generated by defineTool
const countItems = defineTool({
  name: "count_items",
  description: "Count all items in the inventory",
  args: z.object({}),
  load: async (db) => {
    return db.get<{ total: number }>(sql`SELECT COUNT(*) as total FROM items`);
  },
});

const testKitDef = defineKit({
  id: "test-inventory",
  version: "0.1.0",
  name: "Test Inventory",
  description: "Minimal kit for testing createTestKit",
  schema: {},
  migrationSql: `
    CREATE TABLE IF NOT EXISTS items (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      quantity INTEGER DEFAULT 1,
      owner TEXT
    );
  `,
  instructions: "Test kit instructions.",
  tools: [addItem, listItems, countItems],
});

// Helper: extract text from the first text content block
function textOf(result: { content: Array<{ type: string; text?: string }> }) {
  const block = result.content.find((c) => c.type === "text") as
    | { type: "text"; text: string }
    | undefined;
  return block?.text ?? "";
}

// -- Tests --

describe("createTestKit", () => {
  let testKit: TestKit;

  afterEach(async () => {
    if (testKit) await testKit.reset();
  });

  afterAll(async () => {
    if (testKit) await testKit.cleanup();
  });

  it("creates an in-memory database and runs migrations", async () => {
    testKit = await createTestKit(testKitDef);
    expect(testKit.db).toBeDefined();
  });

  it("call() invokes a tool handler and returns KitToolResult", async () => {
    testKit = await createTestKit(testKitDef);
    const result = await testKit.call("add_item", { name: "Widget" });
    expect(result.isError).toBeUndefined();
    expect(textOf(result)).toContain("Widget");
  });

  it("supports direct DB access for assertions", async () => {
    testKit = await createTestKit(testKitDef);
    await testKit.call("add_item", { name: "Gadget", quantity: 5 });

    const rows = await testKit.db.all<{ name: string; quantity: number }>(
      sql`SELECT * FROM items`
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].name).toBe("Gadget");
    expect(rows[0].quantity).toBe(5);
  });

  it("returns error for unknown tool", async () => {
    testKit = await createTestKit(testKitDef);
    const result = await testKit.call("nonexistent_tool", {});
    expect(result.isError).toBe(true);
    expect(textOf(result)).toContain("nonexistent_tool");
    expect(textOf(result)).toContain("Available tools");
  });

  it("validates arguments with Zod", async () => {
    testKit = await createTestKit(testKitDef);
    // name is required string, passing number should fail
    const result = await testKit.call("add_item", { name: 123 as any });
    expect(result.isError).toBe(true);
    expect(textOf(result)).toContain("Invalid arguments");
  });

  it("call() defaults args to empty object", async () => {
    testKit = await createTestKit(testKitDef);
    const result = await testKit.call("list_items");
    expect(result.isError).toBeUndefined();
    expect(textOf(result)).toBe("No items.");
  });

  it("reset() clears all data", async () => {
    testKit = await createTestKit(testKitDef);
    await testKit.call("add_item", { name: "Before Reset" });
    await testKit.reset();
    const result = await testKit.call("list_items");
    expect(textOf(result)).toBe("No items.");
  });

  it("callAs() uses custom context", async () => {
    testKit = await createTestKit(testKitDef);
    await testKit.callAs({ userId: "alice" }, "add_item", { name: "Alice's Item" });

    const rows = await testKit.db.all<{ owner: string }>(
      sql`SELECT owner FROM items`
    );
    expect(rows[0].owner).toBe("alice");
  });

  it("callAs() default userId is test-user", async () => {
    testKit = await createTestKit(testKitDef);
    await testKit.call("add_item", { name: "Default Owner" });

    const rows = await testKit.db.all<{ owner: string }>(
      sql`SELECT owner FROM items`
    );
    expect(rows[0].owner).toBe("test-user");
  });

  it("handles load-only tools (auto-generated handler)", async () => {
    testKit = await createTestKit(testKitDef);
    await testKit.call("add_item", { name: "A", quantity: 3 });
    await testKit.call("add_item", { name: "B", quantity: 7 });

    const result = await testKit.call("count_items");
    expect(result.isError).toBeUndefined();
    const data = JSON.parse(textOf(result));
    expect(data.total).toBe(2);
  });

  it("throws MigrationError for invalid SQL", async () => {
    const badKit = defineKit({
      id: "bad-kit",
      version: "0.0.1",
      name: "Bad Kit",
      description: "Kit with invalid migration SQL",
      schema: {},
      migrationSql: "NOT VALID SQL AT ALL",
      instructions: "",
      tools: [addItem],
    });

    await expect(createTestKit(badKit)).rejects.toThrow(MigrationError);
  });
});
