/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AppData": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BetterAuthUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DevRelay": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "DevRelayStore": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KillSwitch": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "KitCdn": {
      "type": "sst.aws.Router"
      "url": string
    }
    "KitLambdaInfra": {
      "layerArn": string
      "roleArn": string
      "securityGroupIds": any
      "subnetIds": any
      "type": "sst.sst.Linkable"
    }
    "KitVpc": {
      "type": "sst.aws.Vpc"
    }
    "LemonsqueezyApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LemonsqueezyStoreId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LemonsqueezyWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MCPAuthStore": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "McpAllowedOrigins": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpDomain": {
      "type": "sst.aws.Router"
      "url": string
    }
    "McpInternalApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpRouter": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PosthogHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PosthogKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayConnect": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RelayDefault": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RelayDisconnect": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SkillAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TursoAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoDbUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoOrgName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoPlatformApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserKitDbs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "WebAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}

import "sst"
export {}