/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AppData": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Assets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BetterAuthUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KitAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "KitCrm": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitExpense": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitMeeting": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitOutreach": {
      "name": string
      "type": "sst.aws.Function"
    }
    "LemonsqueezyApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LemonsqueezyStoreId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LemonsqueezyWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpAllowedOrigins": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpDomain": {
      "type": "sst.aws.Router"
      "url": string
    }
    "McpInternalApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpRouter": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OAuthStore": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PosthogHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PosthogKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoDbUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoOrgName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoPlatformApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserKitDbs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}