/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AppData": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Assets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "KitCrm": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitExpense": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitMeeting": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitOutreach": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KitRegistry": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "McpRouter": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OAuthStore": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserKitDbs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}