import type { NewSkill, NewKit, NewReview } from "./schema";

const baseCompatibility = ["claude.ai", "Claude Desktop", "Cowork", "Claude Code"];

// --- 6 Free Skills ---

export const seedSkills: NewSkill[] = [
  {
    id: "skill-client-proposal",
    slug: "client-proposal-skill",
    name: "Client Proposal Skill",
    category: "Revenue",
    description: "Generate complete, professional proposals from a brief client description",
    upgradeHook: "Great proposals, but can't remember past proposals or track win rates",
    tags: ["freelancer", "consultant", "agency"],
    compatibility: baseCompatibility,
    exampleInput:
      "Write a proposal for a 3-month brand strategy project for a DTC skincare company. Budget is €15,000. Deliverables: brand audit, positioning framework, messaging guide, visual identity guidelines.",
    exampleOutput:
      "# Brand Strategy Proposal\n\n## Executive Summary\nWe propose a comprehensive brand strategy engagement for [Client] spanning 12 weeks...\n\n## Scope of Work\n### Phase 1: Brand Audit (Weeks 1-3)\n...\n\n## Investment\n| Phase | Deliverable | Fee |\n|-------|-----------|-----|\n| Phase 1 | Brand Audit | €4,500 |\n| Phase 2 | Positioning | €5,500 |\n| Phase 3 | Identity | €5,000 |\n| **Total** | | **€15,000** |",
    whatsInside: [
      { file: "SKILL.md", description: "Core instructions: proposal methodology, structure, tone calibration, pricing psychology" },
      { file: "references/pricing-frameworks.md", description: "Value-based vs hourly vs retainer, when to use each" },
      { file: "references/scope-templates.md", description: "Pre-built scope sections for 8 common project types" },
      { file: "references/objection-handlers.md", description: "Client pushback patterns and response frameworks" },
      { file: "examples/strategy-consulting.md", description: "Full 2-page proposal example" },
      { file: "examples/design-agency.md", description: "Full proposal with visual deliverables emphasis" },
      { file: "examples/tech-freelancer.md", description: "Full proposal with technical milestones" },
      { file: "templates/proposal-structure.md", description: "Section-by-section skeleton with inline instructions" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/client-proposal-skill.zip",
    author: "kitstack",
    fileSize: "18 KB",
    correspondingKitSlug: "crm-kit",
    avgRating: 4.9,
    reviewCount: 142,
    downloadCount: 3280,
  },
  {
    id: "skill-contract-red-flag",
    slug: "contract-red-flag-skill",
    name: "Contract Red Flag Skill",
    category: "Legal",
    description: "Scan contracts for problematic clauses with risk scoring",
    upgradeHook: "Good scan, but can't compare this contract to the last three you signed",
    tags: ["freelancer", "founder", "solopreneur"],
    compatibility: baseCompatibility,
    exampleInput:
      "Review this freelance contract for red flags. [Uploaded: freelance-agreement.pdf]",
    exampleOutput:
      "# Contract Analysis\n\n## Risk Summary\n🔴 **3 Red Flags** | 🟡 **5 Yellow Flags** | 🟢 **12 Green Clauses**\n\n## Red Flags\n### 1. Unlimited Liability (§7.2)\n**Risk: HIGH** — The liability clause has no cap...\n\n⚠️ *Disclaimer: This analysis is not legal advice.*",
    whatsInside: [
      { file: "SKILL.md", description: "Scanning methodology: clause-by-clause analysis, risk scoring framework" },
      { file: "references/red-flag-catalogue.md", description: "30+ problematic clause patterns with explanations" },
      { file: "references/acceptable-ranges.md", description: "Normal ranges for payment terms, liability caps, notice periods" },
      { file: "references/german-contract-law.md", description: "BGB basics, AGB rules (§305-310)" },
      { file: "references/us-contract-basics.md", description: "US/UK common law equivalents" },
      { file: "examples/freelance-contract.md", description: "Full annotated scan with risk scores" },
      { file: "examples/saas-agreement.md", description: "Full annotated scan" },
      { file: "agents/risk-scorer.md", description: "Sub-agent: assigns risk level per clause" },
    ],
    composition: { skillMd: true, references: 4, examples: 2, templates: 0, scripts: 0, agents: 1 },
    s3Key: "skills/contract-red-flag-skill.zip",
    author: "kitstack",
    fileSize: "22 KB",
    correspondingKitSlug: null,
    avgRating: 4.8,
    reviewCount: 98,
    downloadCount: 1940,
  },
  {
    id: "skill-cold-email",
    slug: "cold-email-sequence-skill",
    name: "Cold Email Sequence Skill",
    category: "Sales",
    description: "Write personalized cold email sequences that get replies",
    upgradeHook: "Great sequences, but can't save templates, track prospects, or reuse personalization",
    tags: ["founder", "consultant", "sales"],
    compatibility: baseCompatibility,
    exampleInput:
      "Create a 4-email cold outreach sequence for my consulting firm targeting VP Engineering at Series B SaaS companies.",
    exampleOutput:
      "# Cold Outreach Sequence\n\n## Email 1: Initial Contact\n**Subject:** Quick question about [Company]'s cloud spend\n\nHi [First Name],\n\nNoticed [Company] just raised your Series B — congrats...\n\n## Email 2: Value Add (Day 3)\n...\n\n## Email 3: Social Proof (Day 7)\n...\n\n## Email 4: Breakup (Day 14)\n...",
    whatsInside: [
      { file: "SKILL.md", description: "Sequence logic, personalization rules, subject line principles, CTA calibration" },
      { file: "references/personalization-framework.md", description: "How to weave prospect context naturally" },
      { file: "references/subject-line-patterns.md", description: "15+ proven patterns" },
      { file: "references/cta-spectrum.md", description: "Low → high friction CTA ladder" },
      { file: "examples/consulting-outreach.md", description: "Full 4-email sequence with annotations" },
      { file: "examples/saas-founder-outreach.md", description: "Full 3-email sequence" },
      { file: "examples/agency-new-biz.md", description: "Full 5-email sequence" },
      { file: "agents/personalization-agent.md", description: "Sub-agent for generating prospect hooks" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 0, scripts: 0, agents: 1 },
    s3Key: "skills/cold-email-sequence-skill.zip",
    author: "kitstack",
    fileSize: "16 KB",
    correspondingKitSlug: "cold-outreach-kit",
    avgRating: 4.8,
    reviewCount: 120,
    downloadCount: 2610,
  },
  {
    id: "skill-linkedin-content",
    slug: "linkedin-content-skill",
    name: "LinkedIn Content Skill",
    category: "Marketing",
    description: "Write authentic LinkedIn posts that build authority",
    upgradeHook: "Good posts, but can't remember your voice profile, track past posts, or plan a calendar",
    tags: ["solopreneur", "consultant", "founder"],
    compatibility: baseCompatibility,
    exampleInput:
      "Write a LinkedIn post about why most 'thought leadership' content on LinkedIn is actually just recycled platitudes. Contrarian take, my voice.",
    exampleOutput:
      "90% of LinkedIn thought leadership is a game of telephone.\n\nSomeone reads a Harvard Business Review article. Summarizes it. Posts it without attribution. 50 people reshare it with \"This 👆\"\n\nThat's not thought leadership. That's content laundering.\n\nActual thought leadership starts with one question: What have I learned from doing the work that contradicts what everyone assumes?",
    whatsInside: [
      { file: "SKILL.md", description: "Writing philosophy: observational not instructional, voice calibration, post types" },
      { file: "references/post-frameworks.md", description: "8 proven structures with annotated examples" },
      { file: "references/hook-patterns.md", description: "20+ opening line templates by post type" },
      { file: "references/anti-patterns.md", description: "Banned phrases and engagement-bait patterns" },
      { file: "references/voice-calibration.md", description: "How to extract tone from sample posts" },
      { file: "examples/insight-post.md", description: "Thesis → ELI5 → technical depth → fresh close" },
      { file: "examples/story-post.md", description: "Narrative arc with professional takeaway" },
      { file: "examples/contrarian-post.md", description: "Challenge conventional wisdom" },
      { file: "templates/content-calendar.md", description: "4-week posting plan skeleton" },
    ],
    composition: { skillMd: true, references: 4, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/linkedin-content-skill.zip",
    author: "kitstack",
    fileSize: "24 KB",
    correspondingKitSlug: null,
    avgRating: 4.9,
    reviewCount: 210,
    downloadCount: 4120,
  },
  {
    id: "skill-meeting-action",
    slug: "meeting-action-extractor-skill",
    name: "Meeting Action Extractor Skill",
    category: "Operations",
    description: "Extract decisions, action items, and open questions from notes",
    upgradeHook: "Good extraction, but can't track action items across meetings or see overdue items",
    tags: ["everyone", "operations", "meetings"],
    compatibility: baseCompatibility,
    exampleInput:
      "Here are my rough notes from today's strategy meeting: [pasted meeting notes]",
    exampleOutput:
      "# Meeting Summary — Strategy Meeting\n\n## Decisions Made\n1. ✅ Launch date moved to April 15\n2. ✅ Budget approved for contractor hire\n\n## Action Items\n| # | Action | Owner | Deadline |\n|---|--------|-------|----------|\n| 1 | Draft contractor brief | Sarah | Apr 2 |\n| 2 | Update roadmap | Mike | Apr 3 |\n\n## Open Questions\n- [ ] Do we need legal review for the new TOS?",
    whatsInside: [
      { file: "SKILL.md", description: "Extraction methodology, what qualifies as actionable, owner/deadline inference" },
      { file: "references/output-formats.md", description: "Slack-ready, email-ready, Notion-ready, Markdown table" },
      { file: "references/action-item-rules.md", description: "Qualification criteria" },
      { file: "examples/strategy-meeting.md", description: "Full before/after" },
      { file: "examples/client-call.md", description: "Full before/after" },
    ],
    composition: { skillMd: true, references: 2, examples: 2, templates: 0, scripts: 0, agents: 0 },
    s3Key: "skills/meeting-action-extractor-skill.zip",
    author: "kitstack",
    fileSize: "10 KB",
    correspondingKitSlug: "meeting-action-tracker-kit",
    avgRating: 4.7,
    reviewCount: 315,
    downloadCount: 5340,
  },
  {
    id: "skill-expense-categorizer",
    slug: "expense-categorizer-skill",
    name: "Expense Categorizer Skill",
    category: "Finance",
    description: "Categorize expenses for your Steuerberater with VAT handling",
    upgradeHook: "Good categorization, but can't remember past expenses or generate quarterly summaries",
    tags: ["freelancer", "solopreneur", "german-market"],
    compatibility: baseCompatibility,
    exampleInput:
      "Here's my bank statement CSV from N26 for March. Please categorize all expenses for my Steuerberater using SKR03.",
    exampleOutput:
      "# Expense Report — March 2026\n\n## Summary\n| Category | SKR03 | Count | Total (net) | VAT |\n|----------|-------|-------|-------------|-----|\n| Büromaterial | 4930 | 3 | €127.31 | €24.19 |\n| Software | 4964 | 5 | €312.50 | €59.38 |\n\n⚠️ *This is not tax advice. Please review with your Steuerberater.*",
    whatsInside: [
      { file: "SKILL.md", description: "SKR03/SKR04 mapping logic, VAT rules, flagging for ambiguous items" },
      { file: "references/skr03-categories.md", description: "German standard chart of accounts" },
      { file: "references/vat-rates-de.md", description: "0%/7%/19% decision tree" },
      { file: "references/common-deductions-de.md", description: "Arbeitszimmer, Bewirtung, Reisekosten, etc." },
      { file: "examples/freelancer-monthly.md", description: "Raw list → categorized output" },
      { file: "examples/quarterly-summary.md", description: "Aggregated summary" },
      { file: "scripts/csv-parser.py", description: "Parses bank CSV exports from Sparkasse, N26, ING, Commerzbank, DKB" },
    ],
    composition: { skillMd: true, references: 3, examples: 2, templates: 0, scripts: 1, agents: 0 },
    s3Key: "skills/expense-categorizer-skill.zip",
    author: "kitstack",
    fileSize: "20 KB",
    correspondingKitSlug: "expense-tax-prep-kit",
    avgRating: 4.7,
    reviewCount: 74,
    downloadCount: 1520,
  },
];

// --- 4 Subscription Kits ---

export const seedKits: NewKit[] = [
  {
    id: "kit-crm",
    slug: "crm-kit",
    name: "CRM Kit",
    category: "Revenue",
    description: "Full CRM with contacts, deals, pipeline, and proposals",
    correspondingSkillSlug: "client-proposal-skill",
    replaces: "Pipedrive €24, HubSpot Starter €20",
    savingsPerMonth: 44,
    dbSchema:
      "contacts (id, name, company, email, phone, source, notes, last_contacted_at, created_at)\ndeals (id, name, contact_id FK, value, currency, stage, notes, expected_close_date, created_at, updated_at)\nactivities (id, contact_id FK, deal_id FK, type, description, created_at)\nproposals (id, deal_id FK, content, version, status, created_at)",
    mcpTools: [
      { name: "add_contact", description: "Add a new contact" },
      { name: "list_contacts", description: "List all contacts" },
      { name: "search_contacts", description: "Search contacts by name or company" },
      { name: "add_deal", description: "Create a new deal" },
      { name: "list_deals", description: "List deals with filters" },
      { name: "update_deal", description: "Update deal stage or details" },
      { name: "add_activity", description: "Log an activity" },
      { name: "get_contact_detail", description: "Full contact view with deals and activities" },
      { name: "pipeline_dashboard", description: "View pipeline overview" },
      { name: "generate_proposal", description: "Generate a proposal for a deal" },
      { name: "export", description: "Export contacts and deals as CSV" },
    ],
    mcpApps: [
      { name: "Pipeline Kanban", description: "Visual pipeline board with drag-and-drop" },
      { name: "Contacts Table", description: "Searchable, sortable contacts list" },
      { name: "Contact Detail", description: "Full contact card with deal history" },
      { name: "Dashboard", description: "Deals by stage, value, and recent activity" },
      { name: "Proposal Preview", description: "Formatted proposal view" },
    ],
    tagline: "A real CRM that lives inside your Claude chat.",
    author: "kitstack",
    status: "live",
    subscriberCount: 420,
    avgRating: 4.8,
    reviewCount: 64,
  },
  {
    id: "kit-expense",
    slug: "expense-tax-prep-kit",
    name: "Expense & Tax Prep Kit",
    category: "Finance",
    description: "Track expenses across months with quarterly summaries",
    correspondingSkillSlug: "expense-categorizer-skill",
    replaces: "Lexoffice €14, sevDesk €18",
    savingsPerMonth: 32,
    dbSchema:
      "expenses (id, date, description, amount_gross, amount_net, vat_amount, vat_rate, category, skr03_account, is_private, needs_receipt, notes, source, created_at)\nquarterly_summaries (id, year, quarter, total_gross, total_net, total_vat, category_breakdown JSON, flagged_items JSON, generated_at)\nsettings (key, value)",
    mcpTools: [
      { name: "add_expense", description: "Add a single expense" },
      { name: "import_csv", description: "Import bank CSV (multi-bank parser)" },
      { name: "list_expenses", description: "List expenses with filters" },
      { name: "categorize", description: "Auto-categorize uncategorized expenses" },
      { name: "quarterly_summary", description: "Generate quarterly summary" },
      { name: "export_steuerberater", description: "Export formatted for Steuerberater" },
      { name: "update_expense", description: "Update expense details" },
    ],
    mcpApps: [
      { name: "Expense Table", description: "Sortable table, color-coded by VAT rate" },
      { name: "Category Dashboard", description: "Pie chart, monthly bars, VAT summary" },
      { name: "Import Review", description: "Review and confirm imported expenses" },
      { name: "Steuerberater Export", description: "Formatted export view" },
    ],
    tagline: "German tax prep that remembers the year.",
    author: "kitstack",
    status: "live",
    subscriberCount: 280,
    avgRating: 4.9,
    reviewCount: 38,
  },
  {
    id: "kit-outreach",
    slug: "cold-outreach-kit",
    name: "Cold Outreach Kit",
    category: "Sales",
    description: "Build and manage cold email sequences with prospect tracking",
    correspondingSkillSlug: "cold-email-sequence-skill",
    replaces: "Lavender €29, Instantly €37",
    savingsPerMonth: 66,
    dbSchema:
      "sequences (id, name, target_persona, tone, status, created_at)\nemails (id, sequence_id FK, position, subject, body, delay_days, created_at)\nprospects (id, sequence_id FK, name, company, email, linkedin_url, personalization_hooks JSON, status, created_at)",
    mcpTools: [
      { name: "create_sequence", description: "Create a new email sequence" },
      { name: "generate_emails", description: "Generate emails for a sequence" },
      { name: "list_sequences", description: "List all sequences" },
      { name: "add_prospect", description: "Add a prospect to a sequence" },
      { name: "personalize_for_prospect", description: "Generate personalization hooks" },
      { name: "edit_email", description: "Edit an email in a sequence" },
      { name: "export_sequence", description: "Export sequence for email tool" },
    ],
    mcpApps: [
      { name: "Sequence Builder", description: "Email cards with drag-reorder" },
      { name: "Prospect List", description: "Prospect table with status tracking" },
      { name: "Email Preview", description: "Preview with personalization merge" },
    ],
    tagline: "Sequences that remember who you've written to.",
    author: "kitstack",
    status: "live",
    subscriberCount: 190,
    avgRating: 4.7,
    reviewCount: 24,
  },
  {
    id: "kit-meeting",
    slug: "meeting-action-tracker-kit",
    name: "Meeting Action Tracker Kit",
    category: "Operations",
    description: "Track action items across meetings with persistent history",
    correspondingSkillSlug: "meeting-action-extractor-skill",
    replaces: "Otter.ai $17, Fireflies $19",
    savingsPerMonth: 36,
    dbSchema:
      "meetings (id, title, date, attendees JSON, raw_notes, created_at)\naction_items (id, meeting_id FK, description, owner, deadline, status, created_at)\ndecisions (id, meeting_id FK, description, created_at)",
    mcpTools: [
      { name: "process_meeting", description: "Extract actions from meeting notes" },
      { name: "list_meetings", description: "List all meetings" },
      { name: "get_meeting", description: "Get meeting details with actions" },
      { name: "list_actions", description: "Cross-meeting action items" },
      { name: "update_action", description: "Mark action item as done" },
      { name: "open_items_summary", description: "Summary of all open action items" },
    ],
    mcpApps: [
      { name: "Meeting Summary", description: "Decisions box, action items table, open questions" },
      { name: "Action Tracker", description: "Cross-meeting action items dashboard" },
      { name: "Meeting History", description: "List of past meetings" },
    ],
    tagline: "Action items that survive past the meeting.",
    author: "kitstack",
    status: "live",
    subscriberCount: 340,
    avgRating: 4.8,
    reviewCount: 52,
  },
];

// --- Seed Reviews ---

export const seedReviews: NewReview[] = [
  // Skill reviews: client-proposal-skill
  {
    id: "review-skill-proposal-1",
    targetType: "skill",
    targetSlug: "client-proposal-skill",
    userId: "seed-user-1",
    userName: "Lena K.",
    userRole: "Brand consultant",
    rating: 5,
    text: "Saved me 2 hours on my last proposal. The structure is spot-on and the tone matched my voice.",
    verified: true,
  },
  {
    id: "review-skill-proposal-2",
    targetType: "skill",
    targetSlug: "client-proposal-skill",
    userId: "seed-user-2",
    userName: "Marco S.",
    userRole: "Solo dev",
    rating: 5,
    text: "I used to spend forever scoping projects. Now I paste 4 lines and get a full proposal back.",
    verified: true,
  },
  {
    id: "review-skill-proposal-3",
    targetType: "skill",
    targetSlug: "client-proposal-skill",
    userId: "seed-user-3",
    userName: "Dana A.",
    userRole: "Agency owner",
    rating: 4,
    text: "Great for the basics. Would love a few more industry-specific templates, but the framework is solid.",
    verified: true,
  },
  // Kit reviews: crm-kit
  {
    id: "review-kit-crm-1",
    targetType: "kit",
    targetSlug: "crm-kit",
    userId: "seed-user-4",
    userName: "Mira S.",
    userRole: "Freelance Designer",
    rating: 5,
    text: `Replaced Pipedrive entirely. I just say "log that call" and it's in the CRM. The pipeline kanban inside Claude is wild.`,
    verified: true,
  },
  {
    id: "review-kit-crm-2",
    targetType: "kit",
    targetSlug: "crm-kit",
    userId: "seed-user-5",
    userName: "Jan P.",
    userRole: "Agency Founder",
    rating: 5,
    text: `The proposal generator alone is worth it. But having it connected to a real contact database? That's the upgrade that sticks.`,
    verified: true,
  },
  {
    id: "review-kit-crm-3",
    targetType: "kit",
    targetSlug: "crm-kit",
    userId: "seed-user-6",
    userName: "Anja K.",
    userRole: "Ops Manager",
    rating: 4,
    text: "Solid kit. Wish it had calendar integration, but the team says it's coming. Database export works perfectly.",
    verified: true,
  },
];
