import type { NewSkill, NewKit } from "../web/src/db/schema";

const baseCompatibility = ["claude.ai", "Claude Desktop", "Cowork", "Claude Code"];

// --- 6 Free Skills ---

export const seedSkills: NewSkill[] = [
  {
    id: "skill-client-proposal",
    slug: "client-proposal-skill",
    name: "Client Proposal Skill",
    category: "Revenue",
    description: "Generate complete, professional proposals from a brief client description",
    upgradeHook: "Great proposals, but can't remember past proposals or track win rates",
    tags: ["freelancer", "consultant", "agency"],
    compatibility: baseCompatibility,
    exampleInput:
      "Write a proposal for a 3-month brand strategy project for a DTC skincare company. Budget is €15,000. Deliverables: brand audit, positioning framework, messaging guide, visual identity guidelines.",
    exampleOutput:
      "# Brand Strategy Proposal\n\n## Executive Summary\nWe propose a comprehensive brand strategy engagement for [Client] spanning 12 weeks...\n\n## Scope of Work\n### Phase 1: Brand Audit (Weeks 1-3)\n...\n\n## Investment\n| Phase | Deliverable | Fee |\n|-------|-----------|-----|\n| Phase 1 | Brand Audit | €4,500 |\n| Phase 2 | Positioning | €5,500 |\n| Phase 3 | Identity | €5,000 |\n| **Total** | | **€15,000** |",
    whatsInside: [
      { file: "SKILL.md", description: "Core instructions: proposal methodology, structure, tone calibration, pricing psychology" },
      { file: "references/pricing-frameworks.md", description: "Value-based vs hourly vs retainer, when to use each" },
      { file: "references/scope-templates.md", description: "Pre-built scope sections for 8 common project types" },
      { file: "references/objection-handlers.md", description: "Client pushback patterns and response frameworks" },
      { file: "examples/strategy-consulting.md", description: "Full 2-page proposal example" },
      { file: "examples/design-agency.md", description: "Full proposal with visual deliverables emphasis" },
      { file: "examples/tech-freelancer.md", description: "Full proposal with technical milestones" },
      { file: "templates/proposal-structure.md", description: "Section-by-section skeleton with inline instructions" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/client-proposal-skill.zip",
    author: "kitstack",
    fileSize: "18 KB",
    correspondingKitSlug: "crm-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-contract-red-flag",
    slug: "contract-red-flag-skill",
    name: "Contract Red Flag Skill",
    category: "Legal",
    description: "Scan contracts for problematic clauses with risk scoring",
    upgradeHook: "Good scan, but can't compare this contract to the last three you signed",
    tags: ["freelancer", "founder", "solopreneur"],
    compatibility: baseCompatibility,
    exampleInput:
      "Review this freelance contract for red flags. [Uploaded: freelance-agreement.pdf]",
    exampleOutput:
      "# Contract Analysis\n\n## Risk Summary\n🔴 **3 Red Flags** | 🟡 **5 Yellow Flags** | 🟢 **12 Green Clauses**\n\n## Red Flags\n### 1. Unlimited Liability (§7.2)\n**Risk: HIGH** — The liability clause has no cap...\n\n⚠️ *Disclaimer: This analysis is not legal advice.*",
    whatsInside: [
      { file: "SKILL.md", description: "Scanning methodology: clause-by-clause analysis, risk scoring framework" },
      { file: "references/red-flag-catalogue.md", description: "30+ problematic clause patterns with explanations" },
      { file: "references/acceptable-ranges.md", description: "Normal ranges for payment terms, liability caps, notice periods" },
      { file: "references/german-contract-law.md", description: "BGB basics, AGB rules (§305-310)" },
      { file: "references/us-contract-basics.md", description: "US/UK common law equivalents" },
      { file: "examples/freelance-contract.md", description: "Full annotated scan with risk scores" },
      { file: "examples/saas-agreement.md", description: "Full annotated scan" },
      { file: "agents/risk-scorer.md", description: "Sub-agent: assigns risk level per clause" },
    ],
    composition: { skillMd: true, references: 4, examples: 2, templates: 0, scripts: 0, agents: 1 },
    s3Key: "skills/contract-red-flag-skill.zip",
    author: "kitstack",
    fileSize: "22 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-cold-email",
    slug: "cold-email-sequence-skill",
    name: "Cold Email Sequence Skill",
    category: "Sales",
    description: "Write personalized cold email sequences that get replies",
    upgradeHook: "Great sequences, but can't save templates, track prospects, or reuse personalization",
    tags: ["founder", "consultant", "sales"],
    compatibility: baseCompatibility,
    exampleInput:
      "Create a 4-email cold outreach sequence for my consulting firm targeting VP Engineering at Series B SaaS companies.",
    exampleOutput:
      "# Cold Outreach Sequence\n\n## Email 1: Initial Contact\n**Subject:** Quick question about [Company]'s cloud spend\n\nHi [First Name],\n\nNoticed [Company] just raised your Series B — congrats...\n\n## Email 2: Value Add (Day 3)\n...\n\n## Email 3: Social Proof (Day 7)\n...\n\n## Email 4: Breakup (Day 14)\n...",
    whatsInside: [
      { file: "SKILL.md", description: "Sequence logic, personalization rules, subject line principles, CTA calibration" },
      { file: "references/personalization-framework.md", description: "How to weave prospect context naturally" },
      { file: "references/subject-line-patterns.md", description: "15+ proven patterns" },
      { file: "references/cta-spectrum.md", description: "Low → high friction CTA ladder" },
      { file: "examples/consulting-outreach.md", description: "Full 4-email sequence with annotations" },
      { file: "examples/saas-founder-outreach.md", description: "Full 3-email sequence" },
      { file: "examples/agency-new-biz.md", description: "Full 5-email sequence" },
      { file: "agents/personalization-agent.md", description: "Sub-agent for generating prospect hooks" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 0, scripts: 0, agents: 1 },
    s3Key: "skills/cold-email-sequence-skill.zip",
    author: "kitstack",
    fileSize: "16 KB",
    correspondingKitSlug: "cold-outreach-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-linkedin-content",
    slug: "linkedin-content-skill",
    name: "LinkedIn Content Skill",
    category: "Marketing",
    description: "Write authentic LinkedIn posts that build authority",
    upgradeHook: "Good posts, but can't remember your voice profile, track past posts, or plan a calendar",
    tags: ["solopreneur", "consultant", "founder"],
    compatibility: baseCompatibility,
    exampleInput:
      "Write a LinkedIn post about why most 'thought leadership' content on LinkedIn is actually just recycled platitudes. Contrarian take, my voice.",
    exampleOutput:
      "90% of LinkedIn thought leadership is a game of telephone.\n\nSomeone reads a Harvard Business Review article. Summarizes it. Posts it without attribution. 50 people reshare it with \"This 👆\"\n\nThat's not thought leadership. That's content laundering.\n\nActual thought leadership starts with one question: What have I learned from doing the work that contradicts what everyone assumes?",
    whatsInside: [
      { file: "SKILL.md", description: "Writing philosophy: observational not instructional, voice calibration, post types" },
      { file: "references/post-frameworks.md", description: "8 proven structures with annotated examples" },
      { file: "references/hook-patterns.md", description: "20+ opening line templates by post type" },
      { file: "references/anti-patterns.md", description: "Banned phrases and engagement-bait patterns" },
      { file: "references/voice-calibration.md", description: "How to extract tone from sample posts" },
      { file: "examples/insight-post.md", description: "Thesis → ELI5 → technical depth → fresh close" },
      { file: "examples/story-post.md", description: "Narrative arc with professional takeaway" },
      { file: "examples/contrarian-post.md", description: "Challenge conventional wisdom" },
      { file: "templates/content-calendar.md", description: "4-week posting plan skeleton" },
    ],
    composition: { skillMd: true, references: 4, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/linkedin-content-skill.zip",
    author: "kitstack",
    fileSize: "24 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-meeting-action",
    slug: "meeting-action-extractor-skill",
    name: "Meeting Action Extractor Skill",
    category: "Operations",
    description: "Extract decisions, action items, and open questions from notes",
    upgradeHook: "Good extraction, but can't track action items across meetings or see overdue items",
    tags: ["everyone", "operations", "meetings"],
    compatibility: baseCompatibility,
    exampleInput:
      "Here are my rough notes from today's strategy meeting: [pasted meeting notes]",
    exampleOutput:
      "# Meeting Summary — Strategy Meeting\n\n## Decisions Made\n1. ✅ Launch date moved to April 15\n2. ✅ Budget approved for contractor hire\n\n## Action Items\n| # | Action | Owner | Deadline |\n|---|--------|-------|----------|\n| 1 | Draft contractor brief | Sarah | Apr 2 |\n| 2 | Update roadmap | Mike | Apr 3 |\n\n## Open Questions\n- [ ] Do we need legal review for the new TOS?",
    whatsInside: [
      { file: "SKILL.md", description: "Extraction methodology, what qualifies as actionable, owner/deadline inference" },
      { file: "references/output-formats.md", description: "Slack-ready, email-ready, Notion-ready, Markdown table" },
      { file: "references/action-item-rules.md", description: "Qualification criteria" },
      { file: "examples/strategy-meeting.md", description: "Full before/after" },
      { file: "examples/client-call.md", description: "Full before/after" },
    ],
    composition: { skillMd: true, references: 2, examples: 2, templates: 0, scripts: 0, agents: 0 },
    s3Key: "skills/meeting-action-extractor-skill.zip",
    author: "kitstack",
    fileSize: "10 KB",
    correspondingKitSlug: "meeting-action-tracker-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-expense-categorizer",
    slug: "expense-categorizer-skill",
    name: "Expense Categorizer Skill",
    category: "Finance",
    description: "Categorize expenses for your Steuerberater with VAT handling",
    upgradeHook: "Good categorization, but can't remember past expenses or generate quarterly summaries",
    tags: ["freelancer", "solopreneur", "german-market"],
    compatibility: baseCompatibility,
    exampleInput:
      "Here's my bank statement CSV from N26 for March. Please categorize all expenses for my Steuerberater using SKR03.",
    exampleOutput:
      "# Expense Report — March 2026\n\n## Summary\n| Category | SKR03 | Count | Total (net) | VAT |\n|----------|-------|-------|-------------|-----|\n| Büromaterial | 4930 | 3 | €127.31 | €24.19 |\n| Software | 4964 | 5 | €312.50 | €59.38 |\n\n⚠️ *This is not tax advice. Please review with your Steuerberater.*",
    whatsInside: [
      { file: "SKILL.md", description: "SKR03/SKR04 mapping logic, VAT rules, flagging for ambiguous items" },
      { file: "references/skr03-categories.md", description: "German standard chart of accounts" },
      { file: "references/vat-rates-de.md", description: "0%/7%/19% decision tree" },
      { file: "references/common-deductions-de.md", description: "Arbeitszimmer, Bewirtung, Reisekosten, etc." },
      { file: "examples/freelancer-monthly.md", description: "Raw list → categorized output" },
      { file: "examples/quarterly-summary.md", description: "Aggregated summary" },
      { file: "scripts/csv-parser.py", description: "Parses bank CSV exports from Sparkasse, N26, ING, Commerzbank, DKB" },
    ],
    composition: { skillMd: true, references: 3, examples: 2, templates: 0, scripts: 1, agents: 0 },
    s3Key: "skills/expense-categorizer-skill.zip",
    author: "kitstack",
    fileSize: "20 KB",
    correspondingKitSlug: "expense-tax-prep-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  // --- 14 New Skills (Wave 1-3) ---

  {
    id: "skill-invoice-generator",
    slug: "invoice-generator-skill",
    name: "Invoice Generator",
    category: "Finance",
    description: "Generate professional, legally compliant invoices as HTML artifacts from minimal input — supports German (§14 UStG), US, and UK requirements",
    upgradeHook: "Great invoices, but can't remember your bank details, tax number, or standard rates",
    tags: ["freelancer", "solopreneur", "german-market"],
    compatibility: baseCompatibility,
    exampleInput:
      "Invoice Müller & Partner GmbH for 40 hours UX design at €110 in April. Add a workshop day for €950.",
    exampleOutput:
      "A complete, styled HTML invoice artifact with:\n- Sender/recipient blocks\n- Line items table with subtotals\n- 19% USt calculation\n- Bank details (IBAN/BIC)\n- Gesamtbetrag: 6.366,50 €\n- Print-ready with KitStack design language",
    whatsInside: [
      { file: "SKILL.md", description: "Billing specialist persona, §14 UStG compliance, info gathering, generation process" },
      { file: "references/invoice-legal-requirements.md", description: "Mandatory fields by jurisdiction (DE, US, UK)" },
      { file: "references/pricing-display-patterns.md", description: "Number formatting, table layout, currency display" },
      { file: "references/payment-terms-reference.md", description: "Net 14/30/60, Skonto, late payment (§288 BGB)" },
      { file: "examples/freelancer-monthly-invoice.md", description: "Full German freelancer invoice example" },
      { file: "examples/agency-project-invoice.md", description: "Multi-phase agency project invoice" },
      { file: "examples/international-invoice.md", description: "Cross-border reverse charge invoice" },
      { file: "scripts/invoice-builder.py", description: "JSON → HTML invoice generator with KitStack styling" },
      { file: "assets/invoice-template.html", description: "Professional HTML template with print styles" },
      { file: "templates/invoice-data-structure.md", description: "JSON schema for invoice data" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 1, agents: 0 },
    s3Key: "skills/invoice-generator-skill.zip",
    author: "kitstack",
    fileSize: "32 KB",
    correspondingKitSlug: "expense-tax-prep-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-e-rechnung",
    slug: "e-rechnung-skill",
    name: "E-Rechnung / XRechnung",
    category: "Finance",
    description: "Generate XRechnung-compliant XML invoices and validate against German e-invoicing standards (§14 UStG, EN 16931)",
    upgradeHook: "Great compliance tool, but can't remember your Leitweg-IDs, client details, or invoice history",
    tags: ["freelancer", "german-market", "compliance"],
    compatibility: baseCompatibility,
    exampleInput:
      "Ich muss eine XRechnung an das Bundesamt erstellen. Leitweg-ID 0204:991-54321-89. 40 Stunden IT-Beratung, €130/Std.",
    exampleOutput:
      "Complete UBL 2.1 XML with all mandatory BT fields, plus validation report:\n✅ PASS — 18 checks passed, 0 failed\nIncludes: CustomizationID, Leitweg-ID routing, tax calculation, IBAN payment details",
    whatsInside: [
      { file: "SKILL.md", description: "E-invoicing compliance specialist, XRechnung vs ZUGFeRD, generation process" },
      { file: "references/xrechnung-spec.md", description: "All BT codes, mandatory fields, XML structure" },
      { file: "references/ustg-14-requirements.md", description: "§14 UStG Pflichtangaben (German)" },
      { file: "references/zugferd-overview.md", description: "ZUGFeRD profiles, when to use which" },
      { file: "references/leitweg-id-guide.md", description: "Leitweg-ID format, lookup, validation" },
      { file: "examples/freelancer-xrechnung.md", description: "Freelancer → Behörde complete walkthrough" },
      { file: "examples/b2b-zugferd-invoice.md", description: "B2B ZUGFeRD with embedded XML" },
      { file: "examples/cross-border-eu-invoice.md", description: "EU reverse charge e-invoice" },
      { file: "scripts/xrechnung-generator.py", description: "Generates XRechnung UBL 2.1 XML from JSON" },
      { file: "scripts/xrechnung-validator.py", description: "Validates XML against XRechnung rules" },
      { file: "templates/xrechnung-field-mapping.md", description: "User inputs → BT field mapping table" },
    ],
    composition: { skillMd: true, references: 4, examples: 3, templates: 1, scripts: 2, agents: 0 },
    s3Key: "skills/e-rechnung-skill.zip",
    author: "kitstack",
    fileSize: "38 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-follow-up-drafter",
    slug: "follow-up-drafter-skill",
    name: "Follow-Up Drafter",
    category: "Sales",
    description: "Draft professional follow-up emails from meeting notes — extracts decisions, action items, and next steps",
    upgradeHook: "Great follow-ups, but can't remember your relationship history or past conversations",
    tags: ["everyone", "consultant", "freelancer"],
    compatibility: baseCompatibility,
    exampleInput:
      "Here are my notes from the discovery call with Sarah at Greenfield Ventures: [messy meeting notes]",
    exampleOutput:
      "Subject: Great connecting today — next steps for Greenfield\n\nHi Sarah,\n\nThank you for the conversation earlier...\n\n## Key Takeaways\n1. Your team is currently...\n\n## Action Items\n| Action | Owner | Deadline |\n|--------|-------|----------|\n| Send proposal draft | Me | Friday |",
    whatsInside: [
      { file: "SKILL.md", description: "Executive assistant persona, 5-step generation process, tone calibration" },
      { file: "references/follow-up-frameworks.md", description: "Frameworks for 6 meeting types" },
      { file: "references/tone-calibration-guide.md", description: "Match tone to relationship stage and outcome" },
      { file: "references/action-item-formatting.md", description: "Action item presentation patterns" },
      { file: "examples/client-discovery-followup.md", description: "Discovery call → polished follow-up" },
      { file: "examples/internal-strategy-followup.md", description: "Strategy meeting → internal recap" },
      { file: "examples/sales-demo-followup.md", description: "Sales demo → prospect follow-up" },
      { file: "templates/follow-up-structure.md", description: "Universal email skeleton" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/follow-up-drafter-skill.zip",
    author: "kitstack",
    fileSize: "16 KB",
    correspondingKitSlug: "crm-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-scope-of-work",
    slug: "scope-of-work-skill",
    name: "Scope of Work Generator",
    category: "Revenue",
    description: "Generate complete, client-ready SOW documents with deliverables, timelines, milestones, and terms",
    upgradeHook: "Great SOWs, but can't remember past project scopes or track what worked",
    tags: ["freelancer", "consultant", "agency"],
    compatibility: baseCompatibility,
    exampleInput:
      "SOW for rebuilding the corporate website for FreshFoods GmbH. Budget €35,000, timeline 12 weeks.",
    exampleOutput:
      "# Scope of Work — FreshFoods GmbH Website Redesign\n\n## 1. Project Overview\n...\n## 3. Scope of Work\n### In Scope\n- 14 page templates...\n### Out of Scope\n- Content writing...\n## 5. Timeline & Milestones\n| Phase | Duration | Deliverables | Payment |",
    whatsInside: [
      { file: "SKILL.md", description: "Project management consultant persona, 10-section SOW methodology" },
      { file: "references/sow-legal-essentials.md", description: "IP, liability, termination, change orders" },
      { file: "references/scope-definition-patterns.md", description: "In/out scope, acceptance criteria" },
      { file: "references/milestone-frameworks.md", description: "Phase structures by project type" },
      { file: "examples/web-development-sow.md", description: "Full SOW for website rebuild" },
      { file: "examples/brand-strategy-sow.md", description: "Full SOW for brand positioning" },
      { file: "examples/consulting-retainer-sow.md", description: "Full SOW for fractional CTO" },
      { file: "templates/sow-structure.md", description: "10-section skeleton with instructions" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/scope-of-work-skill.zip",
    author: "kitstack",
    fileSize: "22 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-brand-voice",
    slug: "brand-voice-foundation-skill",
    name: "Brand Voice Foundation",
    category: "Marketing",
    description: "Define your unique brand voice through a guided interview — tone, vocabulary, and writing style distilled into a reusable guide",
    upgradeHook: "Amazing voice guide, but it disappears when this conversation ends — the Content Planner kit remembers it forever",
    tags: ["solopreneur", "consultant", "founder"],
    compatibility: baseCompatibility,
    exampleInput:
      "I want to define my brand voice. I'm a SaaS founder writing on LinkedIn and our blog.",
    exampleOutput:
      "I'll guide you through 8 questions to define your voice. Let's start:\n\n**Who is your primary audience?**\n\n[After interview...]\n\n# Brand Voice Guide — Maya Chen\n## Voice Summary\nConfident but approachable. Technical depth without jargon...\n## Dimensions\n| Dimension | Score | Rule |\n|-----------|-------|------|\n| Formality | 4/10 | First names, contractions OK |",
    whatsInside: [
      { file: "SKILL.md", description: "Brand strategist persona, interview overview, 8 voice dimensions" },
      { file: "agents/voice-interviewer.md", description: "8-question guided interview, one at a time" },
      { file: "references/voice-dimensions.md", description: "8 dimensions with 1-10 scales and examples" },
      { file: "references/tone-spectrum-examples.md", description: "5 voice archetypes with 20+ examples" },
      { file: "references/vocabulary-frameworks.md", description: "Words-we-use / words-we-never-use framework" },
      { file: "examples/tech-founder-voice.md", description: "SaaS founder interview → voice guide" },
      { file: "examples/consultant-voice.md", description: "Management consultant voice guide" },
      { file: "examples/creative-agency-voice.md", description: "Design agency voice guide" },
      { file: "templates/brand-voice-guide.md", description: "Voice profile document template" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 1 },
    s3Key: "skills/brand-voice-foundation-skill.zip",
    author: "kitstack",
    fileSize: "20 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-mahnwesen",
    slug: "mahnwesen-assistant-skill",
    name: "Mahnwesen Assistant",
    category: "Legal",
    description: "Generate the correct German dunning letter sequence with legally correct language and Verzugszinsen calculation per §§286-288 BGB",
    upgradeHook: "Great dunning letters, but can't track which clients are overdue or remind you to escalate",
    tags: ["freelancer", "german-market", "solopreneur"],
    compatibility: baseCompatibility,
    exampleInput:
      "Mein Kunde Müller GmbH hat Rechnung RE-2026-018 über €3.500 nicht bezahlt. Fällig seit 4 Wochen.",
    exampleOutput:
      "Based on the timeline, you should send a **1. Mahnung**.\n\n---\n\n**1. Mahnung**\n\nSehr geehrte Damen und Herren,\n\ntrotz unserer Zahlungserinnerung vom...\n\n---\n\n**Verzugszinsen:** €46,32 (11,27% p.a. × 30 Tage)\n**Mahnpauschale:** €40,00 (§288 Abs. 5 BGB)",
    whatsInside: [
      { file: "SKILL.md", description: "German business law specialist, 4-stage dunning sequence" },
      { file: "references/bgb-286-verzug.md", description: "§286 BGB: when Verzug begins, Mahnung requirements" },
      { file: "references/verzugszinsen-berechnung.md", description: "§288 BGB interest calculation" },
      { file: "references/mahnbescheid-guide.md", description: "Online filing via mahngerichte.de" },
      { file: "references/inkasso-vs-anwalt.md", description: "When to escalate, cost comparison" },
      { file: "examples/zahlungserinnerung-example.md", description: "Friendly payment reminder" },
      { file: "examples/erste-mahnung-example.md", description: "Formal 1. Mahnung" },
      { file: "examples/letzte-mahnung-example.md", description: "Final warning with legal consequences" },
      { file: "scripts/verzugszinsen-rechner.py", description: "Interest calculator with Basiszinssatz" },
      { file: "templates/zahlungserinnerung.md", description: "Friendly reminder letter template" },
      { file: "templates/erste-mahnung.md", description: "First dunning letter template" },
      { file: "templates/zweite-mahnung.md", description: "Second dunning letter template" },
      { file: "templates/letzte-mahnung.md", description: "Final dunning letter template" },
    ],
    composition: { skillMd: true, references: 4, examples: 3, templates: 4, scripts: 1, agents: 0 },
    s3Key: "skills/mahnwesen-assistant-skill.zip",
    author: "kitstack",
    fileSize: "28 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-client-onboarding",
    slug: "client-onboarding-skill",
    name: "Client Onboarding Checklist",
    category: "Operations",
    description: "Generate structured client onboarding sequences customized by project type and industry",
    upgradeHook: "Good checklists, but can't remember your standard process or adapt it per client automatically",
    tags: ["freelancer", "consultant", "agency"],
    compatibility: baseCompatibility,
    exampleInput:
      "New web development client: FreshFoods GmbH, €25K project, 10-week timeline. Generate my onboarding checklist.",
    exampleOutput:
      "# Client Onboarding — FreshFoods GmbH\n\n## Phase 1: Welcome (Day 1-2)\n- [ ] Send welcome email with project overview\n- [ ] Share access request list (CMS, hosting, analytics)\n...\n## Phase 3: Kickoff (Week 1)\n- [ ] Run 60-min kickoff meeting\n- [ ] Confirm milestones and payment schedule",
    whatsInside: [
      { file: "SKILL.md", description: "Operations consultant persona, 5-phase methodology" },
      { file: "references/onboarding-phases.md", description: "5 phases with tasks and timing" },
      { file: "references/industry-checklists.md", description: "Variations by industry" },
      { file: "references/client-communication-cadence.md", description: "When to email/call/send docs" },
      { file: "examples/web-dev-onboarding.md", description: "Full web dev onboarding checklist" },
      { file: "examples/consulting-onboarding.md", description: "Consulting engagement onboarding" },
      { file: "examples/retainer-onboarding.md", description: "Retainer client onboarding" },
      { file: "templates/onboarding-checklist.md", description: "Phase-by-phase checklist template" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/client-onboarding-skill.zip",
    author: "kitstack",
    fileSize: "18 KB",
    correspondingKitSlug: "crm-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-pricing-strategy",
    slug: "pricing-strategy-modeler-skill",
    name: "Pricing Strategy Modeler",
    category: "Finance",
    description: "Model different pricing scenarios — hourly vs project vs retainer vs value-based — with break-even analysis",
    upgradeHook: "Great modeling, but can't remember what you actually charged past clients or track profitability",
    tags: ["freelancer", "consultant", "agency"],
    compatibility: baseCompatibility,
    exampleInput:
      "I charge €100/hr as a UX designer, work about 30 hours a week. I want to earn €120K/year. Should I switch to project-based pricing?",
    exampleOutput:
      "# Pricing Analysis\n\n## Current Model: Hourly (€100/hr)\n- Billable hours: 30/week × 46 weeks = 1,380 hrs\n- Revenue: €138,000\n- After expenses (~€18K): **€120,000** ✅\n\n## Scenario: Project-Based\n...\n\n## Recommendation\nProject-based pricing would increase your effective rate to €135/hr...",
    whatsInside: [
      { file: "SKILL.md", description: "Pricing consultant persona, 4-step analysis methodology" },
      { file: "references/pricing-models-compared.md", description: "Deep comparison of all pricing models" },
      { file: "references/break-even-analysis.md", description: "Fixed costs, utilization, effective rate formulas" },
      { file: "references/rate-benchmarks.md", description: "Market rates by role and geography (DE, US, UK)" },
      { file: "references/pricing-psychology.md", description: "Anchoring, framing, decoy effect" },
      { file: "examples/freelancer-rate-analysis.md", description: "Full freelancer pricing scenario" },
      { file: "examples/agency-project-pricing.md", description: "Agency hourly → project transition" },
      { file: "examples/consultant-value-pricing.md", description: "Value-based pricing model" },
      { file: "templates/pricing-comparison-table.md", description: "Side-by-side scenario comparison" },
    ],
    composition: { skillMd: true, references: 4, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/pricing-strategy-modeler-skill.zip",
    author: "kitstack",
    fileSize: "24 KB",
    correspondingKitSlug: "expense-tax-prep-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-blog-from-outline",
    slug: "blog-from-outline-skill",
    name: "Blog Post from Outline",
    category: "Marketing",
    description: "Turn rough outlines into structured blog post drafts with SEO optimization and readability tuning",
    upgradeHook: "Good drafts, but can't track your content pipeline or remember what topics you've covered",
    tags: ["solopreneur", "consultant", "founder"],
    compatibility: baseCompatibility,
    exampleInput:
      "Write a how-to post from this outline:\n- Why freelancers should raise rates\n- Signs you're undercharging\n- How to have the conversation\n- Rate increase email template",
    exampleOutput:
      "# How to Raise Your Freelance Rates (Without Losing Clients)\n\n**Meta description:** A step-by-step guide to raising your freelance rates...\n\n## Why Most Freelancers Undercharge\nIf you haven't raised your rates in the last 12 months...\n\n[~1,200 words with SEO-optimized headers, internal linking suggestions, and a CTA]",
    whatsInside: [
      { file: "SKILL.md", description: "Content strategist persona, 5 structure patterns, SEO integration" },
      { file: "references/seo-essentials.md", description: "On-page SEO, keywords, headers, linking" },
      { file: "references/blog-structure-patterns.md", description: "How-to, listicle, deep-dive, comparison, opinion" },
      { file: "references/readability-guidelines.md", description: "Sentence length, Flesch-Kincaid targets" },
      { file: "examples/how-to-post.md", description: "Full ~1,200 word how-to post" },
      { file: "examples/opinion-post.md", description: "Full ~800 word opinion piece" },
      { file: "examples/comparison-post.md", description: "Full ~1,000 word comparison post" },
      { file: "templates/blog-post-structure.md", description: "Universal blog skeleton with checklists" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/blog-from-outline-skill.zip",
    author: "kitstack",
    fileSize: "22 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-case-study",
    slug: "case-study-writer-skill",
    name: "Case Study Writer",
    category: "Marketing",
    description: "Turn project outcomes into structured case studies with compelling metrics and client quotes",
    upgradeHook: "Great case studies, but can't pull project details from your tracker automatically",
    tags: ["agency", "consultant", "freelancer"],
    compatibility: baseCompatibility,
    exampleInput:
      "Write a case study about our CRM implementation for a Berlin real estate agency. They went from spreadsheets to a custom system. 40% faster lead response, 25% more closed deals.",
    exampleOutput:
      "# From Spreadsheet Chaos to 25% More Closed Deals\n*How a Berlin real estate agency transformed their sales process*\n\n## The Client\nA 15-person agency managing 200+ property listings...\n\n## The Challenge\n...\n\n## The Results\n| Metric | Before | After | Impact |\n|--------|--------|-------|--------|\n| Lead response time | 4.2 hours | 2.5 hours | **40% faster** |",
    whatsInside: [
      { file: "SKILL.md", description: "B2B content strategist persona, 3 frameworks, data presentation" },
      { file: "references/case-study-frameworks.md", description: "CSR, STAR, Before/After/Bridge" },
      { file: "references/data-presentation.md", description: "How to present metrics compellingly" },
      { file: "references/client-approval-guide.md", description: "Quotes, naming, anonymization" },
      { file: "examples/saas-implementation.md", description: "Full SaaS implementation case study" },
      { file: "examples/brand-redesign.md", description: "Full brand redesign case study" },
      { file: "examples/consulting-engagement.md", description: "Full consulting case study" },
      { file: "templates/case-study-structure.md", description: "Multiple framework templates" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/case-study-writer-skill.zip",
    author: "kitstack",
    fileSize: "20 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-weekly-review",
    slug: "weekly-review-skill",
    name: "Weekly Review Framework",
    category: "Operations",
    description: "Guided end-of-week reflection with structured wins, challenges, lessons, and priorities for next week",
    upgradeHook: "Good reflections, but can't see your reviews from the past month or spot patterns over time",
    tags: ["everyone", "freelancer", "founder"],
    compatibility: baseCompatibility,
    exampleInput:
      "Let's do my weekly review. I'm a freelance UX designer with 3 active clients.",
    exampleOutput:
      "Let's reflect on your week. I'll ask one question at a time.\n\n**What was your biggest win this week?**\n\n[After guided session...]\n\n# Weekly Review — May 2, 2026\n## Wins\n- Delivered FreshFoods wireframes ahead of schedule\n## Challenges\n- Context-switching between 3 clients draining energy\n## Next Week Priorities\n1. Block mornings for deep work",
    whatsInside: [
      { file: "SKILL.md", description: "Executive coach persona, 6-phase review methodology" },
      { file: "agents/review-facilitator.md", description: "Guided one-question-at-a-time reflection" },
      { file: "references/reflection-frameworks.md", description: "Start/Stop/Continue, Plus/Delta, 5 Whys" },
      { file: "references/priority-setting-methods.md", description: "Eisenhower, MoSCoW, energy management" },
      { file: "references/pattern-recognition-prompts.md", description: "Questions that surface recurring themes" },
      { file: "examples/freelancer-weekly-review.md", description: "Full freelancer review session" },
      { file: "examples/founder-weekly-review.md", description: "Full founder review session" },
    ],
    composition: { skillMd: true, references: 3, examples: 2, templates: 0, scripts: 0, agents: 1 },
    s3Key: "skills/weekly-review-skill.zip",
    author: "kitstack",
    fileSize: "18 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-competitive-teardown",
    slug: "competitive-teardown-skill",
    name: "Competitive Teardown",
    category: "Revenue",
    description: "Structured competitor analysis with positioning, pricing intelligence, and differentiation opportunities",
    upgradeHook: "Good analysis, but can't track your competitive landscape over time or detect changes",
    tags: ["founder", "consultant", "freelancer"],
    compatibility: baseCompatibility,
    exampleInput:
      "Analyze my competitor BigDesign Studio. I run a 6-person design agency in Berlin focused on B2B SaaS.",
    exampleOutput:
      "# Competitive Teardown — BigDesign Studio\n\n## Overview\n- Founded: 2019, Berlin\n- Team: ~20 people\n- Focus: Enterprise design systems\n\n## Positioning Analysis\n...\n\n## Your Differentiation Opportunities\n1. **Niche deeper into B2B SaaS** — they're generalists\n2. **Speed as a weapon** — your 6-person team ships faster",
    whatsInside: [
      { file: "SKILL.md", description: "Competitive intelligence analyst persona, 6-layer methodology" },
      { file: "references/competitive-analysis-frameworks.md", description: "Porter's Five Forces, SWOT, value curves" },
      { file: "references/pricing-intelligence.md", description: "Pricing analysis and reverse engineering" },
      { file: "references/differentiation-mapping.md", description: "Finding your unique angle" },
      { file: "examples/saas-competitor-teardown.md", description: "Full SaaS competitor analysis" },
      { file: "examples/agency-competitor-teardown.md", description: "Agency positioning analysis" },
      { file: "examples/freelancer-market-analysis.md", description: "Freelancer market map" },
      { file: "templates/teardown-report.md", description: "10-section report skeleton" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/competitive-teardown-skill.zip",
    author: "kitstack",
    fileSize: "22 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-pitch-deck-reviewer",
    slug: "pitch-deck-reviewer-skill",
    name: "Pitch Deck Reviewer",
    category: "Revenue",
    description: "Review pitch decks for narrative clarity, slide structure, and investor objections with actionable feedback",
    upgradeHook: "Good reviews, but can't track feedback across versions or remember what changed",
    tags: ["founder", "consultant", "agency"],
    compatibility: baseCompatibility,
    exampleInput:
      "Review my seed round pitch deck. Here are the slides: [10 slides described with content]",
    exampleOutput:
      "# Pitch Deck Review — InvoiceBot Seed Round\n\n## Overall Score: 6.5/10\n**Narrative:** The story is there but buried...\n\n## Slide-by-Slide Review\n### Slide 1: Title\n**Score: 7/10** — Clean, but add a one-line value prop\n\n### Slide 2: Problem\n**Score: 5/10** — Too abstract. Add a specific...\n\n## Top 3 Issues\n1. No traction slide...",
    whatsInside: [
      { file: "SKILL.md", description: "Presentation coach persona, 4-step review methodology" },
      { file: "references/deck-structure-patterns.md", description: "Sequoia format, Guy Kawasaki 10/20/30" },
      { file: "references/investor-objection-catalogue.md", description: "20+ objections with preemptive content" },
      { file: "references/storytelling-principles.md", description: "Narrative arc, data viz, one-idea-per-slide" },
      { file: "examples/seed-round-review.md", description: "Full seed deck slide-by-slide review" },
      { file: "examples/service-pitch-review.md", description: "Agency pitch review" },
      { file: "templates/deck-review-report.md", description: "Review report template" },
    ],
    composition: { skillMd: true, references: 3, examples: 2, templates: 1, scripts: 0, agents: 0 },
    s3Key: "skills/pitch-deck-reviewer-skill.zip",
    author: "kitstack",
    fileSize: "20 KB",
    correspondingKitSlug: null,
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
  {
    id: "skill-kit-showcase",
    slug: "kit-showcase-skill",
    name: "Kit Showcase / Playground",
    category: "Operations",
    description: "Interactive demo that shows what KitStack kits can do — try a mini CRM, expense tracker, or decision journal in a single session",
    upgradeHook: "You just experienced the value of structured data — now imagine it persists forever",
    tags: ["everyone"],
    compatibility: baseCompatibility,
    exampleInput:
      "Show me what the CRM kit can do.",
    exampleOutput:
      "Let's try it! Tell me about a recent client interaction.\n\n[After demo...]\n\nYou just added a contact, logged an interaction, and asked 'who haven't I followed up with?' — and I gave you the answer.\n\nNow here's the thing: when this conversation ends, everything we just built disappears.\n\nThat's what a kit solves. It remembers.",
    whatsInside: [
      { file: "SKILL.md", description: "Product demonstrator, 4-phase demo methodology" },
      { file: "agents/demo-conductor.md", description: "Guided demo with natural memory moment" },
      { file: "references/kit-capabilities.md", description: "All 5 kits: tools, views, use cases" },
      { file: "references/demo-scenarios.md", description: "Pre-built demo scripts per kit" },
      { file: "references/persistence-value-prop.md", description: "The 'memory wall' explanation" },
      { file: "examples/crm-mini-demo.md", description: "CRM demo walkthrough" },
      { file: "examples/expense-mini-demo.md", description: "Expense tracking demo" },
      { file: "examples/decision-journal-mini-demo.md", description: "Decision journal demo" },
    ],
    composition: { skillMd: true, references: 3, examples: 3, templates: 0, scripts: 0, agents: 1 },
    s3Key: "skills/kit-showcase-skill.zip",
    author: "kitstack",
    fileSize: "16 KB",
    correspondingKitSlug: "crm-kit",
    avgRating: 0,
    reviewCount: 0,
    downloadCount: 0,
  },
];

// --- 4 Subscription Kits ---

export const seedKits: NewKit[] = [
  {
    id: "kit-crm",
    slug: "crm-kit",
    name: "CRM Kit",
    category: "Revenue",
    description: "Full CRM with contacts, deals, pipeline, and proposals",
    correspondingSkillSlug: "client-proposal-skill",
    replaces: "Pipedrive €24, HubSpot Starter €20",
    savingsPerMonth: 44,
    dbSchema:
      "contacts (id, name, company, email, phone, source, notes, last_contacted_at, created_at)\ndeals (id, name, contact_id FK, value, currency, stage, notes, expected_close_date, created_at, updated_at)\nactivities (id, contact_id FK, deal_id FK, type, description, created_at)\nproposals (id, deal_id FK, content, version, status, created_at)",
    mcpTools: [
      { name: "add_contact", description: "Add a new contact" },
      { name: "list_contacts", description: "List all contacts" },
      { name: "search_contacts", description: "Search contacts by name or company" },
      { name: "add_deal", description: "Create a new deal" },
      { name: "list_deals", description: "List deals with filters" },
      { name: "update_deal", description: "Update deal stage or details" },
      { name: "add_activity", description: "Log an activity" },
      { name: "get_contact_detail", description: "Full contact view with deals and activities" },
      { name: "pipeline_dashboard", description: "View pipeline overview" },
      { name: "generate_proposal", description: "Generate a proposal for a deal" },
      { name: "export", description: "Export contacts and deals as CSV" },
    ],
    mcpApps: [
      { name: "Pipeline Kanban", description: "Visual pipeline board with drag-and-drop" },
      { name: "Contacts Table", description: "Searchable, sortable contacts list" },
      { name: "Contact Detail", description: "Full contact card with deal history" },
      { name: "Dashboard", description: "Deals by stage, value, and recent activity" },
      { name: "Proposal Preview", description: "Formatted proposal view" },
    ],
    tagline: "A real CRM that lives inside your Claude chat.",
    author: "kitstack",
    status: "live",
    subscriberCount: 0,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: "kit-expense",
    slug: "expense-tax-prep-kit",
    name: "Expense & Tax Prep Kit",
    category: "Finance",
    description: "Track expenses across months with quarterly summaries",
    correspondingSkillSlug: "expense-categorizer-skill",
    replaces: "Lexoffice €14, sevDesk €18",
    savingsPerMonth: 32,
    dbSchema:
      "expenses (id, date, description, amount_gross, amount_net, vat_amount, vat_rate, category, skr03_account, is_private, needs_receipt, notes, source, created_at)\nquarterly_summaries (id, year, quarter, total_gross, total_net, total_vat, category_breakdown JSON, flagged_items JSON, generated_at)\nsettings (key, value)",
    mcpTools: [
      { name: "add_expense", description: "Add a single expense" },
      { name: "import_csv", description: "Import bank CSV (multi-bank parser)" },
      { name: "list_expenses", description: "List expenses with filters" },
      { name: "categorize", description: "Auto-categorize uncategorized expenses" },
      { name: "quarterly_summary", description: "Generate quarterly summary" },
      { name: "export_steuerberater", description: "Export formatted for Steuerberater" },
      { name: "update_expense", description: "Update expense details" },
    ],
    mcpApps: [
      { name: "Expense Table", description: "Sortable table, color-coded by VAT rate" },
      { name: "Category Dashboard", description: "Pie chart, monthly bars, VAT summary" },
      { name: "Import Review", description: "Review and confirm imported expenses" },
      { name: "Steuerberater Export", description: "Formatted export view" },
    ],
    tagline: "German tax prep that remembers the year.",
    author: "kitstack",
    status: "live",
    subscriberCount: 0,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: "kit-outreach",
    slug: "cold-outreach-kit",
    name: "Cold Outreach Kit",
    category: "Sales",
    description: "Build and manage cold email sequences with prospect tracking",
    correspondingSkillSlug: "cold-email-sequence-skill",
    replaces: "Lavender €29, Instantly €37",
    savingsPerMonth: 66,
    dbSchema:
      "sequences (id, name, target_persona, tone, status, created_at)\nemails (id, sequence_id FK, position, subject, body, delay_days, created_at)\nprospects (id, sequence_id FK, name, company, email, linkedin_url, personalization_hooks JSON, status, created_at)",
    mcpTools: [
      { name: "create_sequence", description: "Create a new email sequence" },
      { name: "generate_emails", description: "Generate emails for a sequence" },
      { name: "list_sequences", description: "List all sequences" },
      { name: "add_prospect", description: "Add a prospect to a sequence" },
      { name: "personalize_for_prospect", description: "Generate personalization hooks" },
      { name: "edit_email", description: "Edit an email in a sequence" },
      { name: "export_sequence", description: "Export sequence for email tool" },
    ],
    mcpApps: [
      { name: "Sequence Builder", description: "Email cards with drag-reorder" },
      { name: "Prospect List", description: "Prospect table with status tracking" },
      { name: "Email Preview", description: "Preview with personalization merge" },
    ],
    tagline: "Sequences that remember who you've written to.",
    author: "kitstack",
    status: "live",
    subscriberCount: 0,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: "kit-meeting",
    slug: "meeting-action-tracker-kit",
    name: "Meeting Action Tracker Kit",
    category: "Operations",
    description: "Track action items across meetings with persistent history",
    correspondingSkillSlug: "meeting-action-extractor-skill",
    replaces: "Otter.ai $17, Fireflies $19",
    savingsPerMonth: 36,
    dbSchema:
      "meetings (id, title, date, attendees JSON, raw_notes, created_at)\naction_items (id, meeting_id FK, description, owner, deadline, status, created_at)\ndecisions (id, meeting_id FK, description, created_at)",
    mcpTools: [
      { name: "process_meeting", description: "Extract actions from meeting notes" },
      { name: "list_meetings", description: "List all meetings" },
      { name: "get_meeting", description: "Get meeting details with actions" },
      { name: "list_actions", description: "Cross-meeting action items" },
      { name: "update_action", description: "Mark action item as done" },
      { name: "open_items_summary", description: "Summary of all open action items" },
    ],
    mcpApps: [
      { name: "Meeting Summary", description: "Decisions box, action items table, open questions" },
      { name: "Action Tracker", description: "Cross-meeting action items dashboard" },
      { name: "Meeting History", description: "List of past meetings" },
    ],
    tagline: "Action items that survive past the meeting.",
    author: "kitstack",
    status: "live",
    subscriberCount: 0,
    avgRating: 0,
    reviewCount: 0,
  },
];

